// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OJTManagementAPI.DataContext;

namespace OJTManagementAPI.Migrations
{
    [DbContext(typeof(OjtManagementContext))]
    [Migration("20220713011039_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OJTManagementAPI.Entities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CompanyId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("OJTManagementAPI.Entities.Major", b =>
                {
                    b.Property<int>("MajorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MajorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MajorId");

                    b.ToTable("Major");
                });

            modelBuilder.Entity("OJTManagementAPI.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("OJTManagementAPI.Entities.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SemesterNumber")
                        .HasColumnType("int");

                    b.HasKey("SemesterId");

                    b.ToTable("Semester");
                });

            modelBuilder.Entity("OJTManagementAPI.Entities.SemesterCompany", b =>
                {
                    b.Property<int>("SemesterCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("SemesterId")
                        .HasColumnType("int");

                    b.HasKey("SemesterCompanyId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SemesterId");

                    b.ToTable("SemesterCompany");
                });

            modelBuilder.Entity("OJTManagementAPI.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MajorId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("UserId");

                    b.HasIndex("MajorId");

                    b.HasIndex("RoleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("OJTManagementAPI.Entities.UserCompany", b =>
                {
                    b.Property<int>("UserCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserCompanyId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCompany");
                });

            modelBuilder.Entity("OJTManagementAPI.Entities.UserSemester", b =>
                {
                    b.Property<int>("UserSemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserSemesterId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSemester");
                });

            modelBuilder.Entity("OJTManagementAPI.Entities.SemesterCompany", b =>
                {
                    b.HasOne("OJTManagementAPI.Entities.Company", "Company")
                        .WithMany("SemesterCompanies")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK__SemesterC__Compa__398D8EEE");

                    b.HasOne("OJTManagementAPI.Entities.Semester", "Semester")
                        .WithMany("SemesterCompanies")
                        .HasForeignKey("SemesterId")
                        .HasConstraintName("FK__SemesterC__Semes__38996AB5");

                    b.Navigation("Company");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("OJTManagementAPI.Entities.User", b =>
                {
                    b.HasOne("OJTManagementAPI.Entities.Major", "Major")
                        .WithMany("Users")
                        .HasForeignKey("MajorId")
                        .HasConstraintName("FK__User__MajorId__2C3393D0")
                        .IsRequired();

                    b.HasOne("OJTManagementAPI.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__User__RoleId__2B3F6F97")
                        .IsRequired();

                    b.Navigation("Major");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OJTManagementAPI.Entities.UserCompany", b =>
                {
                    b.HasOne("OJTManagementAPI.Entities.Company", "Company")
                        .WithMany("UserCompanies")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK__UserCompa__Compa__35BCFE0A");

                    b.HasOne("OJTManagementAPI.Entities.User", "User")
                        .WithMany("UserCompanies")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__UserCompa__UserI__34C8D9D1");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OJTManagementAPI.Entities.UserSemester", b =>
                {
                    b.HasOne("OJTManagementAPI.Entities.Semester", "Semester")
                        .WithMany("UserSemesters")
                        .HasForeignKey("SemesterId")
                        .HasConstraintName("FK__UserSemes__Semes__31EC6D26");

                    b.HasOne("OJTManagementAPI.Entities.User", "User")
                        .WithMany("UserSemesters")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__UserSemes__UserI__30F848ED");

                    b.Navigation("Semester");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OJTManagementAPI.Entities.Company", b =>
                {
                    b.Navigation("SemesterCompanies");

                    b.Navigation("UserCompanies");
                });

            modelBuilder.Entity("OJTManagementAPI.Entities.Major", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("OJTManagementAPI.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("OJTManagementAPI.Entities.Semester", b =>
                {
                    b.Navigation("SemesterCompanies");

                    b.Navigation("UserSemesters");
                });

            modelBuilder.Entity("OJTManagementAPI.Entities.User", b =>
                {
                    b.Navigation("UserCompanies");

                    b.Navigation("UserSemesters");
                });
#pragma warning restore 612, 618
        }
    }
}
